"""Leakage-resistant walk-forward research protocol."""

from btc_short_horizon.research.walk_forward import (
    ResearchSample,
    WalkForwardConfig,
    WalkForwardFold,
    WalkForwardPlan,
    build_walk_forward_plan,
    select_complete_group_indices,
)
from btc_short_horizon.research.pipeline import (
    DirectionDataset,
    HoldoutPrediction,
    OofPrediction,
    SealedHoldoutModelRun,
    WalkForwardModelRun,
    run_sealed_holdout_model,
    run_walk_forward_model,
)
from btc_short_horizon.research.gates import (
    CalibrationBinEvidence,
    DirectionGateEvidence,
    GateDecision,
    MakerGateEvidence,
    OpeningMispricingGateEvidence,
    evaluate_direction_gate,
    evaluate_maker_gate,
    evaluate_opening_mispricing_gate,
)
from btc_short_horizon.research.opening_evidence import (
    ForwardBookEventLoad,
    ForwardRawEvent,
    ForwardRawEventLoad,
    OpeningMarketObservation,
    PmxtBookEventLoad,
    RawPayloadError,
    TokenBookStateEvent,
    build_opening_market_observations,
    load_forward_raw_events,
    load_forward_polymarket_book_events,
    pmxt_order_book_state_events,
)
from btc_short_horizon.research.opening_features import (
    ForwardFeatureSourceSummary,
    ForwardFeatureStateEvent,
    ForwardOpeningFeatureBuild,
    build_forward_opening_feature_observations,
)
from btc_short_horizon.research.opening_dataset import (
    OpeningDirectionDatasetBuild,
    build_opening_direction_dataset,
)
from btc_short_horizon.research.opening_runtime import build_opening_proxy_prediction
from btc_short_horizon.research.opening_model_gate import (
    CandidateEvaluation,
    CandidatePairedEvidence,
    CandidateSelectionDecision,
    build_direction_gate_artifact,
    calibration_slope,
    paired_daily_block_bootstrap,
    select_direction_candidate,
    target_confidence_bands,
    weighted_calibration_error,
)
from btc_short_horizon.research.opening_market_relative import (
    MarketRelativeFeatureFamily,
    OpeningMarketRelativeDatasetBuild,
    build_opening_market_relative_datasets,
    opening_market_relative_feature_schema,
)
from btc_short_horizon.research.opening_market_relative_research import (
    MARKET_RELATIVE_LOGISTIC_ABLATIONS,
    MarketRelativeAblation,
    MarketRelativeCandidateMetrics,
    MarketRelativeDevelopmentRun,
    MarketRelativeSealedHoldoutRun,
    build_market_relative_artifact_contract,
    evaluate_market_relative_research_gate,
    market_relative_development_report,
    run_market_relative_development,
    run_market_relative_sealed_holdout,
)

__all__ = [
    "MARKET_RELATIVE_LOGISTIC_ABLATIONS",
    "CalibrationBinEvidence",
    "CandidateEvaluation",
    "CandidatePairedEvidence",
    "CandidateSelectionDecision",
    "DirectionDataset",
    "DirectionGateEvidence",
    "GateDecision",
    "HoldoutPrediction",
    "MakerGateEvidence",
    "MarketRelativeAblation",
    "MarketRelativeCandidateMetrics",
    "MarketRelativeDevelopmentRun",
    "MarketRelativeSealedHoldoutRun",
    "MarketRelativeFeatureFamily",
    "OofPrediction",
    "OpeningMispricingGateEvidence",
    "OpeningMarketObservation",
    "OpeningMarketRelativeDatasetBuild",
    "OpeningDirectionDatasetBuild",
    "ForwardBookEventLoad",
    "ForwardFeatureSourceSummary",
    "ForwardFeatureStateEvent",
    "ForwardOpeningFeatureBuild",
    "ForwardRawEvent",
    "ForwardRawEventLoad",
    "PmxtBookEventLoad",
    "RawPayloadError",
    "ResearchSample",
    "TokenBookStateEvent",
    "WalkForwardConfig",
    "WalkForwardFold",
    "WalkForwardPlan",
    "build_walk_forward_plan",
    "build_opening_market_observations",
    "build_opening_market_relative_datasets",
    "build_market_relative_artifact_contract",
    "build_opening_proxy_prediction",
    "build_opening_direction_dataset",
    "build_direction_gate_artifact",
    "build_forward_opening_feature_observations",
    "load_forward_raw_events",
    "load_forward_polymarket_book_events",
    "pmxt_order_book_state_events",
    "select_complete_group_indices",
    "WalkForwardModelRun",
    "SealedHoldoutModelRun",
    "run_sealed_holdout_model",
    "run_walk_forward_model",
    "evaluate_direction_gate",
    "evaluate_maker_gate",
    "evaluate_opening_mispricing_gate",
    "evaluate_market_relative_research_gate",
    "market_relative_development_report",
    "calibration_slope",
    "paired_daily_block_bootstrap",
    "select_direction_candidate",
    "target_confidence_bands",
    "weighted_calibration_error",
    "opening_market_relative_feature_schema",
    "run_market_relative_development",
    "run_market_relative_sealed_holdout",
]
